<a href="https://colab.research.google.com/github/niqueve/BootcampSantander/blob/main/Desafio_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importações

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Dados

In [5]:
from google.colab import drive  #-----------------importa drive para uso de arquivos no script
drive.mount('/content/drive')

Mounted at /content/drive

In [37]:
dados = pd.read_excel('/content/drive/MyDrive/Bootcamp2023/Desafios/Normal-Climatologica-ESTAÇÕES.xlsx')

In [40]:
dados.columns = ['Número', 'Código', 'Nome da Estação','UF','Latitude','Longitude','Altitude','Inicio_operação','Fim_operação','Situação']

In [41]:
dados

,Número,Código,Nome da Estação,UF,Latitude,Longitude,Altitude,Inicio_operação,Fim_operação,Situação
0,Estações Convêncionais,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nº,Código,Nome da Estação,UF,Latitude,Longitude,Atitude,Inicio Operação,Fim Operação,Situação
2,1,82989,AGUA BRANCA,AL,-9.264722,-37.938056,603.42,1928-05-05 00:00:00,NaN,Operante
3,2,83249,ALAGOINHAS,BA,-12.148611,-38.425278,129.78,1931-01-01 00:00:00,2021-07-15 00:00:00,Fechada
4,3,82353,ALTAMIRA,PA,-3.214167,-52.213056,101.51,1927-04-24 00:00:00,2021-07-25 00:00:00,Fechada
...,...,...,...,...,...,...,...,...,...,...
268,267,83642,VICOSA,MG,-20.7625,-42.863889,697.53,1919-10-01 00:00:00,2018-03-08 00:00:00,Fechada
269,268,83648,VITORIA,ES,-20.315833,-40.316944,36.2,1923-11-20 00:00:00,NaN,Operante
270,269,83344,VITORIA DA CONQUISTA,BA,-14.886389,-40.801389,879.47,1936-01-01 00:00:00,NaN,Operante
271,270,83623,VOTUPORANGA,SP,-20.439722,-49.983611,510.41,1976-07-05 00:00:00,NaN,Operante
272,271,82376,ZE DOCA,MA,-3.269212,-45.651007,46.71,1970-08-25 00:00:00,NaN,Operante

# Resultados

In [46]:
dados['UF'].describe()

count     272
unique     27
top        MG
freq       47
Name: UF, dtype: object

In [47]:
uf = list(dados['UF'])

In [49]:
def estados (uf):
  tabela = []
  for n in uf:
    if n in tabela:
      None
    else:
      tabela.append(n)
  return tabela

In [50]:
estados_uf = estados(uf) # Lista com todos os estados

In [52]:
estados_uf = estados_uf[2:] # retirar Nan

In [53]:
estados_uf

['AL',
 'BA',
 'PA',
 'RJ',
 'MA',
 'RN',
 'SE',
 'MG',
 'GO',
 'TO',
 'PE',
 'PB',
 'RS',
 'CE',
 'AM',
 'ES',
 'RR',
 'PI',
 'DF',
 'PR',
 'SP',
 'SC',
 'MT',
 'AC',
 'AP',
 'MS']

In [73]:
def total_estacoes (estados,dados):
  tabela = []
  for n in estados:
    total = dados.count(n)
    tabela.append([n,total])
  dataframe = pd.DataFrame(data = tabela, columns = ['Estados','Total de Estações'])
  return dataframe

In [74]:
total = total_estacoes(estados_uf,uf)

In [79]:
total

   Estados  Total de Estações
0       AL                  5
1       BA                 27
2       PA                 15
3       RJ                 17
4       MA                 12
5       RN                  7
6       SE                  3
7       MG                 47
8       GO                 10
9       TO                  6
10      PE                  9
11      PB                  6
12      RS                 17
13      CE                 11
14      AM                 14
15      ES                  6
16      RR                  2
17      PI                 14
18      DF                  2
19      PR                  8
20      SP                  9
21      SC                  7
22      MT                 10
23      AC                  3
24      AP                  1
25      MS                  3

In [78]:
total.to_csv('total_estações.csv') # salva arquivo com total de estações em csv